/**
 * Minimal pure-JS PDF builder for account statements (no native deps).
 * Produces a simple multi-page text PDF suitable for download.
 */

function escapePdfText(s) {
  return String(s ?? '')
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)');
}

function formatMoney(amount, currency = 'USD') {
  const n = Number(amount);
  if (!Number.isFinite(n)) return String(amount);
  try {
    return new Intl.NumberFormat('en-GB', {
      style: 'currency',
      currency: currency || 'USD',
      minimumFractionDigits: 2,
    }).format(n);
  } catch {
    return `${n.toFixed(2)} ${currency}`;
  }
}

function formatDate(d) {
  try {
    return new Date(d).toLocaleString('en-GB', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  } catch {
    return String(d);
  }
}

/**
 * @param {{
 *   fullName: string,
 *   email: string,
 *   account: { account_number?: string, account_name?: string, currency?: string, balance?: any, routing_number?: string },
 *   transactions: Array<{ created_at?: string, type?: string, description?: string, reference?: string, amount?: any, currency?: string, status?: string }>,
 *   periodLabel: string,
 * }} data
 * @returns {Buffer}
 */
export function buildStatementPdf(data) {
  const { fullName, email, account, transactions = [], periodLabel } = data;
  const currency = account?.currency || 'USD';
  const lines = [];

  lines.push('RUBICON CAPITAL');
  lines.push('Account statement');
  lines.push(`Period: ${periodLabel}`);
  lines.push('');
  lines.push(`Client: ${fullName || '—'}`);
  lines.push(`Email: ${email || '—'}`);
  lines.push(`Account: ${account?.account_number || '—'}`);
  if (account?.routing_number) lines.push(`Routing: ${account.routing_number}`);
  lines.push(`Currency: ${currency}`);
  lines.push(`Balance: ${formatMoney(account?.balance, currency)}`);
  lines.push('');
  lines.push('Date                 Type            Amount              Description');
  lines.push('-'.repeat(78));

  for (const tx of transactions.slice(0, 200)) {
    const date = formatDate(tx.created_at).padEnd(20).slice(0, 20);
    const type = String(tx.type || tx.status || 'tx').padEnd(15).slice(0, 15);
    const amt = formatMoney(tx.amount, tx.currency || currency).padStart(16).slice(0, 16);
    const desc = String(tx.description || tx.reference || '').slice(0, 24);
    lines.push(`${date} ${type} ${amt}  ${desc}`);
  }

  if (!transactions.length) {
    lines.push('(No transactions in this period)');
  }

  lines.push('');
  lines.push('This statement is generated by Rubicon Capital for your records.');
  lines.push('For support: support@rubiconcapital.org');

  // Build PDF content stream (Helvetica, 10pt, top-down)
  const pageWidth = 612;
  const pageHeight = 792;
  const marginLeft = 40;
  const marginTop = 40;
  const lineHeight = 12;
  const maxLinesPerPage = Math.floor((pageHeight - marginTop * 2) / lineHeight);

  const pages = [];
  for (let i = 0; i < lines.length; i += maxLinesPerPage) {
    pages.push(lines.slice(i, i + maxLinesPerPage));
  }
  if (!pages.length) pages.push(['(empty)']);

  const objects = [];
  // 1: catalog, 2: pages, 3..: page objects + contents

  const pageObjectIds = [];
  const contentObjectIds = [];

  function addObject(str) {
    objects.push(str);
    return objects.length; // 1-based id
  }

  // We'll build content first as strings, then assemble
  const contentStreams = pages.map((pageLines) => {
    let y = pageHeight - marginTop;
    const ops = ['BT', '/F1 10 Tf', `${marginLeft} ${y} Td`];
    pageLines.forEach((line, idx) => {
      if (idx === 0) {
        ops.push(`(${escapePdfText(line)}) Tj`);
      } else {
        ops.push(`0 -${lineHeight} Td (${escapePdfText(line)}) Tj`);
      }
    });
    ops.push('ET');
    return ops.join('\n');
  });

  // Object 1: Catalog
  // Object 2: Pages
  // Then for each page: Page dict + Content stream
  // Font object at end

  // Reserve: we'll construct in order
  // id 1 = Catalog
  // id 2 = Pages  
  // for each page i: pageObj, contentObj
  // last = Font

  const fontId = 3 + pages.length * 2;

  let kids = [];
  for (let i = 0; i < pages.length; i++) {
    const pageId = 3 + i * 2;
    const contentId = pageId + 1;
    pageObjectIds.push(pageId);
    contentObjectIds.push(contentId);
    kids.push(`${pageId} 0 R`);
  }

  const bodyParts = [];
  // obj 1 catalog
  bodyParts.push(`1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n`);
  // obj 2 pages
  bodyParts.push(
    `2 0 obj\n<< /Type /Pages /Kids [${kids.join(' ')}] /Count ${pages.length} >>\nendobj\n`
  );

  for (let i = 0; i < pages.length; i++) {
    const pageId = 3 + i * 2;
    const contentId = pageId + 1;
    const stream = contentStreams[i];
    bodyParts.push(
      `${pageId} 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Contents ${contentId} 0 R /Resources << /Font << /F1 ${fontId} 0 R >> >> >>\nendobj\n`
    );
    bodyParts.push(
      `${contentId} 0 obj\n<< /Length ${Buffer.byteLength(stream, 'utf8')} >>\nstream\n${stream}\nendstream\nendobj\n`
    );
  }

  bodyParts.push(
    `${fontId} 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n`
  );

  const body = bodyParts.join('\n');
  // Build xref
  const header = '%PDF-1.4\n';
  let offset = Buffer.byteLength(header, 'utf8');
  const offsets = [0]; // object 0 free

  // We need per-object offsets — rebuild carefully
  const chunks = [header];
  offset = Buffer.byteLength(header, 'utf8');

  function pushObj(str) {
    offsets.push(offset);
    const part = str.endsWith('\n') ? str : str + '\n';
    chunks.push(part);
    offset += Buffer.byteLength(part, 'utf8');
  }

  pushObj(`1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj`);
  pushObj(`2 0 obj\n<< /Type /Pages /Kids [${kids.join(' ')}] /Count ${pages.length} >>\nendobj`);

  for (let i = 0; i < pages.length; i++) {
    const pageId = 3 + i * 2;
    const contentId = pageId + 1;
    const stream = contentStreams[i];
    pushObj(
      `${pageId} 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Contents ${contentId} 0 R /Resources << /Font << /F1 ${fontId} 0 R >> >> >>\nendobj`
    );
    const streamLen = Buffer.byteLength(stream, 'utf8');
    pushObj(
      `${contentId} 0 obj\n<< /Length ${streamLen} >>\nstream\n${stream}\nendstream\nendobj`
    );
  }
  pushObj(`${fontId} 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj`);

  const xrefStart = offset;
  const objCount = offsets.length; // includes free object 0
  let xref = `xref\n0 ${objCount}\n`;
  xref += `0000000000 65535 f \n`;
  for (let i = 1; i < offsets.length; i++) {
    xref += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`;
  }
  const trailer = `trailer\n<< /Size ${objCount} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`;
  chunks.push(xref);
  chunks.push(trailer);

  return Buffer.from(chunks.join(''), 'utf8');
}
